recipe: default.v1
language: zh
pipeline:
- name: JiebaTokenizer
#  token_pattern: '[^A-Z^a-z^0-9^\u4e00-\u9fa5]'
#  #自定义词典
#  dictionary_path: "path/to/custom/dictionary/dir"
#  #不切分intent
#  "intent_tokenization_flag": False
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: bert/roberta-yto-cls-v3
- name: DIETClassifier
  entity_recognition: False
  constrain_similarities: True
  epochs: 12
#  hidden_layers_sizes: [256,128]
#  text: [256, 128] # 默认[]
  embedding_dimension: 64 # 默认20
  number_of_transformer_layers: 2  # 默认2
  transformer_size: 128 # 默认256
  connection_density: 0.2 # 默认0.2
# - name: SpacyNLP
#   model: zh_core_web_sm  # 注意，不是短杆"-"连接
# - name: SpacyEntityExtractor
#   dimensions: ["PERSON"]
- name: RegexEntityExtractor
  use_word_boundaries: False
  case_sensitive: False
  use_lookup_tables: True
  use_regexes: True
- name: "EntitySynonymMapper"
- name: ResponseSelector
  constrain_similarities: True
  epochs: 12
  retrieval_intent: faq
- name: FallbackClassifier
  threshold: 0.22
  ambiguity_threshold: 0.05
  threshold_faq: 0.5
  ambiguity_threshold_faq: 0.3

policies:
- name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.2
  core_fallback_action_name: action_default_fallback
assistant_id: yto-call-assistant-v0.1-20240226
