recipe: default.v1
language: zh
pipeline:
# - name: rasa.nlu.tokenizers.plant_tokenizer.JiebaTokenizer
- name: JiebaTokenizer
#  token_pattern: '[^A-Z^a-z^0-9^\u4e00-\u9fa5]'
#  #自定义词典
#  dictionary_path: "path/to/custom/dictionary/dir"
#  #不切分intent
#  "intent_tokenization_flag": False
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: bert/roberta-yto-cls-v3
# - name: "CountVectorsFeaturizer"
#   "analyzer": "word"
#   "min_df": 2
#   "max_df": 1000
#   "min_ngram": 1
#   "max_ngram": 3
#   # Set the out-of-vocabulary token
#   "OOV_token": "_oov_"
#   # Whether to use a shared vocab
#   "use_shared_vocab": False
# - name: LogisticRegressionClassifier
#   max_iter: 200
#   solver: lbfgs
#   tol: 0.0005
#   random_state: 42
#   ranking_length: 3
# - name: rasa.nlu.classifiers.logistic_regplus_classifier.LogisticRegressionClassifier
#   max_iter: 200
#   solver: lbfgs
#   tol: 0.0005
#   random_state: 42
#   ranking_length: 3
# - name: rasa.nlu.classifiers.mlp_plus_classifier.MLP_Classifier
#   C: 0.8
#   tol: 0.0005
#   max_iter: 1000
#   ranking_length: 3
- name: rasa.nlu.classifiers.mlp_classifier.MLP_Classifier
  # C: 0.8
  # tol: 0.0005
  # max_iter: 1000
  # ranking_length: 3
# - name: rasa.nlu.classifiers.linearsvc_plus_classifier.LinearSVCClassifier
#   C: 1
#   tol: 0.0005
#   max_iter: 1000
#   ranking_length: 3

# - name: DIETClassifier
#   entity_recognition: False
#   constrain_similarities: True
#   epochs: 32
# #  hidden_layers_sizes: [256,128]
# #  text: [256, 128] # 默认[]
#   embedding_dimension: 128 # 默认20
#   number_of_transformer_layers: 2  # 默认2
#   transformer_size: 128 # 默认256
#   learning_rate: 0.0005 # 默认0.001
#   connection_density: 0.5 # 默认0.2
#   ranking_length: 3
# - name: "SklearnIntentClassifier"
#   # Specifies the list of regularization values to
#   # cross-validate over for C-SVM.
#   # This is used with the ``kernel`` hyperparameter in GridSearchCV.
#   C: [0.8, 1, 2, 5, 10, 20]
#   # Specifies the kernel to use with C-SVM.
#   # This is used with the ``C`` hyperparameter in GridSearchCV.
#   kernels: ["linear"]
#   # Gamma parameter of the C-SVM.
#   "gamma": [0.1]
#   # We try to find a good number of cross folds to use during
#   # intent training, this specifies the max number of folds.
#   "max_cross_validation_folds": 5
#   # Scoring function used for evaluating the hyper parameters.
#   # This can be a name or a function.
#   "scoring_function": "f1_weighted"
# - name: rasa.nlu.classifiers.svc_classifier.SVCClassifier
#   # Specifies the list of regularization values to
#   # cross-validate over for C-SVM.
#   # This is used with the ``kernel`` hyperparameter in GridSearchCV.
#   C: [0.8, 1, 2, 5, 10, 20, 100]
#   # Specifies the kernel to use with C-SVM.
#   # This is used with the ``C`` hyperparameter in GridSearchCV.
#   kernels: ["linear"]
#   # Gamma parameter of the C-SVM.
#   "gamma": [0.1]
#   # We try to find a good number of cross folds to use during
#   # intent training, this specifies the max number of folds.
#   "max_cross_validation_folds": 5
#   # Scoring function used for evaluating the hyper parameters.
#   # This can be a name or a function.
#   "scoring_function": "f1_weighted"
- name: RegexEntityExtractor
  use_word_boundaries: False
  case_sensitive: False
  use_lookup_tables: True
  use_regexes: True
- name: "EntitySynonymMapper"
# - name: ResponseSelector
#   constrain_similarities: True
#   epochs: 15
#   retrieval_intent: faq
- name: FallbackClassifier
  threshold: 0.1
  ambiguity_threshold: 0.01

policies:
# - name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.1
  core_fallback_action_name: action_listen
assistant_id: yto-call-assistant-v0.1-20240226
