version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  file:
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: file
    level: INFO
    filename: logs\rasa.log # 文件名可以根据你的需求修改
    maxBytes: 1048576
    backupCount: 6
    encoding: 'utf8'
loggers:
  rasa:
    handlers: [console, file]
    propagate: no
    level: INFO